### ISSUE TITLE
live-installer: hangs at 'Partitioning'

### ISSUE THREAD

**Issue by ovari** [linuxmint/lmde-3-cinnamon-beta#13]
![lmde3partitioning](https://user-images.githubusercontent.com/17465872/43511407-a9c4ba8c-95bb-11e8-9eec-1ef750af6f67.png)

**Comment by clefebvre** [comment]
Hi @ovari,

Please run "sudo live-installer" from terminal and reproduce the issue. We need an error message/output to understand what's wrong here.

Also give us the exact steps/choices if possible.

**Comment by ovari** [comment]
Thank you @clefebvre for your reply.

Does the `sudo live-installer` use the Desktop Installer or the Calamares Installer?

https://blog.linuxmint.com/?p=3629#comment-145063 and our replies afterwards have some steps that worked. Strangely, we re-install and got different default options with a Swap disk.

The Calamares Installer in the menu worked. Are you planning to remove the Desktop Installer and just use the Calamares Installer? If so, is there a need to debug the Desktop Installer?

HP Stream 11 laptop
Processor: Intel Celeron CPU N2840 @ 2.16GHz x 2
Memory: 1.9 GiB
HDD: 32GB eMMC
Graphics Card: Intel Corporation Atom Z36xxx/Z37xxx Series Graphics & Display

If you would like us to run `sudo live-installer` and provide feedback please advise.

Thank you

**Comment by ovari** [comment]
```
$ sudo live-installer
build_timezones(_installer = <frontend.gtk_interface.InstallerWindow instance at 0x7fcd8784dc20>)
Starting PartitionSetup()
Excluding /dev/sda (detected as the live device)
Can't find model in blkid output: ['disk', 'mmcblk0', '0', '29.1G']
Can't find model in blkid output: ['disk', 'mmcblk0boot0', '0', '4M']
Can't find model in blkid output: ['disk', 'mmcblk0boot1', '0', '4M']
Can't find model in blkid output: ['disk', 'mmcblk0rpmb', '0', '4M']
Can't find model in blkid output: ['loop', 'loop0', '0', '1.5G']
Disks:  [('/dev/mmcblk0', 'mmcblk0 (31 GB)'), ('/dev/mmcblk0boot0', 'mmcblk0boot0 (4 MB)'), ('/dev/mmcblk0boot1', 'mmcblk0boot1 (4 MB)'), ('/dev/mmcblk0rpmb', 'mmcblk0rpmb (4 MB)')]
    Analyzing path='/dev/mmcblk0' description='mmcblk0 (31 GB)'
      - Found the device...
      - Found the disk...
      - Looking at partitions...
           -> 2 free space partitions
           -> 3 primary partitions
           -> 0 logical partitions
           -> 0 raid partitions
           -> 0 LVM partitions
           -> set of 5 partitions
              -> Building partition object for /dev/mmcblk0p2
                  . length 51904307
                  . size_percent 68
                  . size 26.6 GB
                  . name /dev/mmcblk0p2
                  . type ext4
                  . About to mount it...
mount: /dev/mmcblk0p2 is already mounted or /tmp/live-installer/tmpmount busy
       /dev/mmcblk0p2 is already mounted on /media/mint/e54dfcaa-2368-4c04-93b9-dbcd4d358038
                  . size 25413772, free 19662032, self.used_percent 19%, mount_point /media/mint/e54dfcaa-2368-4c04-93b9-dbcd4d358038
                  . About to find more about it...
                  . self.description LMDE 3 Cindy self.os_fs_info : LMDE 3 Cindy (ext4; 26.0 GB; 20.1 GB)
                  . umounting it
                  . done
              -> Building partition object for /dev/mmcblk0p1
                  . length 614401
                  . size_percent 1
                  . size 314.6 MB
                  . name /dev/mmcblk0p1
                  . type fat32
                  . About to mount it...
                  . size 306584, free 306204, self.used_percent 1%, mount_point /tmp/live-installer/tmpmount
                  . About to find more about it...
                  . self.description EFI System Partition self.os_fs_info : EFI System Partition (fat32; 313.9 MB; 313.6 MB)
                  . umounting it
                  . done
              -> Building partition object for /dev/mmcblk0p3
                  . length 8540260
                  . size_percent 11
                  . size 4.4 GB
                  . name /dev/mmcblk0p3
                  . type swap
                  . About to mount it...
mount: unknown filesystem type 'swap'
                  . value error!
                  . self.os_fs_info : swap, self.description swap, self.free_space , self.used_percent 0
                  . umounting it
                  . done
      - Found partitions...
      - Iterating partitions...
        . Appending partition /dev/mmcblk0p1...
        . Appending partition /dev/mmcblk0p2...
        . Appending partition /dev/mmcblk0p3...
      - Loading HTML view...
    Analyzing path='/dev/mmcblk0boot0' description='mmcblk0boot0 (4 MB)'
      - Found the device...
      - Found an issue while looking for the disk: /dev/mmcblk0boot0: unrecognised disk label
Performing a full disk format
Error: Operation not permitted during write on /dev/mmcblk0boot0
mkpart primary 2MB 302MB
Error: /dev/mmcblk0boot0: unrecognised disk label
mkfs.vfat /dev/mmcblk0boot01 -F 32 
mkfs.fat 4.1 (2017-01-24)
mkfs.vfat: unable to open /dev/mmcblk0boot01: No such file or directory
mkpart primary 303MB 2403MB
Error: /dev/mmcblk0boot0: unrecognised disk label
mkswap /dev/mmcblk0boot02
mkswap: cannot open /dev/mmcblk0boot02: No such file or directory
mkpart primary 2404MB 100%
Error: /dev/mmcblk0boot0: unrecognised disk label
mkfs.ext4 -F /dev/mmcblk0boot03
mke2fs 1.43.4 (31-Jan-2017)
The file /dev/mmcblk0boot03 does not exist and no size was specified.
Error: /dev/mmcblk0boot0: unrecognised disk label
Done full disk format
Traceback (most recent call last):
  File "/usr/lib/live-installer/frontend/gtk_interface.py", line 795, in wizard_cb
    partitioning.build_partitions(self)
  File "/usr/lib/live-installer/partitioning.py", line 66, in build_partitions
    partition_setup = PartitionSetup()
  File "/usr/lib/live-installer/partitioning.py", line 250, in __init__
    disk = parted.Disk(disk_device)
  File "/usr/lib/python2.7/dist-packages/parted/decorators.py", line 42, in new
    ret = fn(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/parted/disk.py", line 52, in __init__
    self.__disk = _ped.Disk(device.getPedDevice())
_ped.DiskLabelException: /dev/mmcblk0boot0: unrecognised disk label
```

**Comment by clefebvre** [comment]
Thanks.

**Comment by clefebvre** [comment]
@ovari can you test with this change? 

https://github.com/linuxmint/live-installer/commit/11a73d802a9cb8ea3e0dff3b6134acc0e234a5e8

**Comment by ovari** [comment]
@clefebvre where do we download the iso?

**Comment by clefebvre** [comment]
There's no new ISO yet. You can launch the live session, open Firefox and download this ZIP:

[live-installer.zip](https://github.com/linuxmint/lmde-3-cinnamon-beta/files/2260279/live-installer.zip)

Decompress and install the .deb to replace the ISO version of live-installer with this one (the one in the ZIP contains all the new commits).

Then run sudo live-installer again.

Hopefully with the changes, it should skip the problematic disk instead of crashing.

**Comment by ovari** [comment]
Sorry, don't know how to do what you ask.

Do the files in `live-installer.zip` replace a files in the `LMDE 3 Cinnamon 64-bit` bootable USB?

Or do the files in `live-installer.zip` replace a files in the `lmde-3-cinnamon-64bit-beta.iso`?

Have looked in the folders and couldn't see any `live-installer*` files. Could you please advise the complete folder/directory location?

Thank you

**Comment by clefebvre** [comment]
Sure:

Launch the ISO (i.e. a live session), and within the live session, do all the following:

- Download and decompress the ZIP file
- Go to the decompressed folder and you'll see a .deb file called live-installer_2018.07.28.1_all.deb
- Install this .deb file (either double-click it to install it with gdebi, or use a terminal and use sudo dpkg -i live-installer_2018.07.28.1_all.deb)

Once you've installed the .deb file, the installer within your live session is basically updated (from the version which shipped in the ISO, to the version I just built here and placed on github... and that version contains a fix for the issue you described).

**Comment by ovari** [comment]
Thanks, gets past that error.

There are lots of error dialog boxes when we click on "Edit partitions"

```
$ sudo live-installer
cinnamon-screensaver: no process found
build_timezones(_installer = <frontend.gtk_interface.InstallerWindow instance at 0x7f210a3f7200>)
Starting PartitionSetup()
Excluding /dev/sda (detected as the live device)
Can't find model in blkid output: ['disk', 'mmcblk0', '0', '29.1G']
Can't find model in blkid output: ['disk', 'mmcblk0boot0', '0', '4M']
Can't find model in blkid output: ['disk', 'mmcblk0boot1', '0', '4M']
Can't find model in blkid output: ['disk', 'mmcblk0rpmb', '0', '4M']
Can't find model in blkid output: ['loop', 'loop0', '0', '1.5G']
Disks:  [('/dev/mmcblk0', 'mmcblk0 (31 GB)'), ('/dev/mmcblk0boot0', 'mmcblk0boot0 (4 MB)'), ('/dev/mmcblk0boot1', 'mmcblk0boot1 (4 MB)'), ('/dev/mmcblk0rpmb', 'mmcblk0rpmb (4 MB)')]
    Analyzing path='/dev/mmcblk0' description='mmcblk0 (31 GB)'
      - Found the device...
      - Found the disk...
      - Looking at partitions...
           -> 2 free space partitions
           -> 3 primary partitions
           -> 0 logical partitions
           -> 0 raid partitions
           -> 0 LVM partitions
           -> set of 5 partitions
              -> Building partition object for /dev/mmcblk0p3
                  . length 8540260
                  . size_percent 11
                  . size 4.4 GB
                  . name /dev/mmcblk0p3
                  . type swap
                  . About to mount it...
mount: unknown filesystem type 'swap'
                  . value error!
                  . self.os_fs_info : swap, self.description swap, self.free_space , self.used_percent 0
                  . umounting it
                  . done
              -> Building partition object for /dev/mmcblk0p1
                  . length 614401
                  . size_percent 1
                  . size 314.6 MB
                  . name /dev/mmcblk0p1
                  . type fat32
                  . About to mount it...
                  . size 306584, free 306204, self.used_percent 1%, mount_point /tmp/live-installer/tmpmount
                  . About to find more about it...
                  . self.description EFI System Partition self.os_fs_info : EFI System Partition (fat32; 313.9 MB; 313.6 MB)
                  . umounting it
                  . done
              -> Building partition object for /dev/mmcblk0p2
                  . length 51904307
                  . size_percent 68
                  . size 26.6 GB
                  . name /dev/mmcblk0p2
                  . type ext4
                  . About to mount it...
mount: /dev/mmcblk0p2 is already mounted or /tmp/live-installer/tmpmount busy
       /dev/mmcblk0p2 is already mounted on /media/mint/e54dfcaa-2368-4c04-93b9-dbcd4d358038
                  . size 25413772, free 16587828, self.used_percent 32%, mount_point /media/mint/e54dfcaa-2368-4c04-93b9-dbcd4d358038
                  . About to find more about it...
                  . self.description LMDE 3 Cindy self.os_fs_info : LMDE 3 Cindy (ext4; 26.0 GB; 17.0 GB)
                  . umounting it
                  . done
      - Found partitions...
      - Iterating partitions...
        . Appending partition /dev/mmcblk0p1...
        . Appending partition /dev/mmcblk0p2...
        . Appending partition /dev/mmcblk0p3...
      - Loading HTML view...
    Analyzing path='/dev/mmcblk0boot0' description='mmcblk0boot0 (4 MB)'
      - Found the device...
      - Found an issue while looking for the disk: /dev/mmcblk0boot0: unrecognised disk label
Performing a full disk format
Error: Operation not permitted during write on /dev/mmcblk0boot0
mkpart primary 2MB 302MB
Error: /dev/mmcblk0boot0: unrecognised disk label
mkfs.vfat /dev/mmcblk0boot01 -F 32 
mkfs.fat 4.1 (2017-01-24)
mkfs.vfat: unable to open /dev/mmcblk0boot01: No such file or directory
mkpart primary 303MB 2403MB
Error: /dev/mmcblk0boot0: unrecognised disk label
mkswap /dev/mmcblk0boot02
mkswap: cannot open /dev/mmcblk0boot02: No such file or directory
mkpart primary 2404MB 100%
Error: /dev/mmcblk0boot0: unrecognised disk label
mkfs.ext4 -F /dev/mmcblk0boot03
mke2fs 1.43.4 (31-Jan-2017)
The file /dev/mmcblk0boot03 does not exist and no size was specified.
Error: /dev/mmcblk0boot0: unrecognised disk label
Done full disk format
      - Found another issue while looking for the disk: /dev/mmcblk0boot0: unrecognised disk label
    Analyzing path='/dev/mmcblk0boot1' description='mmcblk0boot1 (4 MB)'
      - Found the device...
      - Found an issue while looking for the disk: /dev/mmcblk0boot1: unrecognised disk label
Performing a full disk format
Error: Operation not permitted during write on /dev/mmcblk0boot1
mkpart primary 2MB 302MB
Error: /dev/mmcblk0boot1: unrecognised disk label
mkfs.vfat /dev/mmcblk0boot11 -F 32 
mkfs.fat 4.1 (2017-01-24)
mkfs.vfat: unable to open /dev/mmcblk0boot11: No such file or directory
mkpart primary 303MB 2403MB
Error: /dev/mmcblk0boot1: unrecognised disk label
mkswap /dev/mmcblk0boot12
mkswap: cannot open /dev/mmcblk0boot12: No such file or directory
mkpart primary 2404MB 100%
Error: /dev/mmcblk0boot1: unrecognised disk label
mkfs.ext4 -F /dev/mmcblk0boot13
mke2fs 1.43.4 (31-Jan-2017)
The file /dev/mmcblk0boot13 does not exist and no size was specified.
Error: /dev/mmcblk0boot1: unrecognised disk label
Done full disk format
      - Found another issue while looking for the disk: /dev/mmcblk0boot1: unrecognised disk label
    Analyzing path='/dev/mmcblk0rpmb' description='mmcblk0rpmb (4 MB)'
      - Found the device...
      - Found an issue while looking for the disk: Failed to read partition table from device /dev/mmcblk0rpmb
Performing a full disk format
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Error: Input/output error during read on /dev/mmcblk0rpmb
Error: Input/output error during write on /dev/mmcblk0rpmb
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
mkpart primary 2MB 302MB
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Error: /dev/mmcblk0rpmb: unrecognised disk label
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
mkfs.vfat /dev/mmcblk0rpmb1 -F 32 
mkfs.fat 4.1 (2017-01-24)
mkfs.vfat: unable to open /dev/mmcblk0rpmb1: No such file or directory
mkpart primary 303MB 2403MB
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Error: /dev/mmcblk0rpmb: unrecognised disk label
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
mkswap /dev/mmcblk0rpmb2
mkswap: cannot open /dev/mmcblk0rpmb2: No such file or directory
mkpart primary 2404MB 100%
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Error: /dev/mmcblk0rpmb: unrecognised disk label
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
mkfs.ext4 -F /dev/mmcblk0rpmb3
mke2fs 1.43.4 (31-Jan-2017)
The file /dev/mmcblk0rpmb3 does not exist and no size was specified.
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Error: /dev/mmcblk0rpmb: unrecognised disk label
Warning: Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Done full disk format
      - Found another issue while looking for the disk: Failed to read partition table from device /dev/mmcblk0rpmb
Finished PartitionSetup()
Loading HTML string
Showing the partition screen
umount: /dev/mmcblk0: not mounted
umount: /dev/mmcblk0boot0: not mounted
umount: /dev/mmcblk0boot1: not mounted
umount: /dev/mmcblk0rpmb: not mounted
Created symlink /run/systemd/system/-.mount → /dev/null.
Created symlink /run/systemd/system/lib-live-mount-medium.mount → /dev/null.
Created symlink /run/systemd/system/lib-live-mount-overlay.mount → /dev/null.
Created symlink /run/systemd/system/lib-live-mount-rootfs-filesystem.squashfs.mount → /dev/null.
Created symlink /run/systemd/system/media-mint-e54dfcaa\x2d2368\x2d4c04\x2d93b9\x2ddbcd4d358038.mount → /dev/null.
Created symlink /run/systemd/system/run-user-1000.mount → /dev/null.
Created symlink /run/systemd/system/tmp.mount → /dev/null.
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Input/output error during read on /dev/mmcblk0rpmb
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
/dev/mmcblk0boot0: unrecognised disk label
/dev/mmcblk0boot1: unrecognised disk label
Input/output error during write on /dev/mmcblk0rpmb
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
/dev/mmcblk0rpmb: unrecognised disk label
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Input/output error during read on /dev/mmcblk0rpmb
Input/output error during read on /dev/mmcblk0rpmb
Input/output error during read on /dev/mmcblk0rpmb
Input/output error during read on /dev/mmcblk0rpmb
Input/output error during read on /dev/mmcblk0rpmb
Input/output error during read on /dev/mmcblk0rpmb
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Removed /run/systemd/system/-.mount.
Removed /run/systemd/system/lib-live-mount-medium.mount.
Removed /run/systemd/system/lib-live-mount-overlay.mount.
Removed /run/systemd/system/lib-live-mount-rootfs-filesystem.squashfs.mount.
Removed /run/systemd/system/media-mint-e54dfcaa\x2d2368\x2d4c04\x2d93b9\x2ddbcd4d358038.mount.
Removed /run/systemd/system/run-user-1000.mount.
Removed /run/systemd/system/tmp.mount.
umount: /dev/mmcblk0: not mounted
umount: /dev/mmcblk0boot0: not mounted
umount: /dev/mmcblk0boot1: not mounted
umount: /dev/mmcblk0rpmb: not mounted
Created symlink /run/systemd/system/-.mount → /dev/null.
Created symlink /run/systemd/system/lib-live-mount-medium.mount → /dev/null.
Created symlink /run/systemd/system/lib-live-mount-overlay.mount → /dev/null.
Created symlink /run/systemd/system/lib-live-mount-rootfs-filesystem.squashfs.mount → /dev/null.
Created symlink /run/systemd/system/media-mint-e54dfcaa\x2d2368\x2d4c04\x2d93b9\x2ddbcd4d358038.mount → /dev/null.
Created symlink /run/systemd/system/run-user-1000.mount → /dev/null.
Created symlink /run/systemd/system/tmp.mount → /dev/null.
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Input/output error during read on /dev/mmcblk0rpmb
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
/dev/mmcblk0boot0: unrecognised disk label
/dev/mmcblk0boot1: unrecognised disk label
Input/output error during write on /dev/mmcblk0rpmb
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
/dev/mmcblk0rpmb: unrecognised disk label
Error fsyncing/closing /dev/mmcblk0rpmb: Input/output error
Input/output error during read on /dev/mmcblk0rpmb
Input/output error during read on /dev/mmcblk0rpmb
Input/output error during read on /dev/mmcblk0rpmb
```

**Comment by clefebvre** [comment]
Cool, marking as fixed.

Edit partitions just launched gparted, that's upstream from us.
